const ADMIN_PERMISSIONS = Object.freeze([
  "USERS_VIEW",
  "USERS_CREATE",
  "USERS_EDIT",
  "USERS_DELETE",
  "USERS_BAN",
  "USERS_ROLE",
  "USERS_PERMISSIONS",
  "USERS_PASSWORD_RESET",
  "PARTNER_MANAGE",
  "CREDITS_ADJUST",
  "ORDERS_MANAGE",
  "PRODUCTS_MANAGE",
  "TICKETS_MANAGE",
  "NOTIFICATIONS_MANAGE",
  "DISCOUNTS_MANAGE",
  "ANALYTICS_VIEW",
  "LOGS_VIEW"
]);

const DEFAULT_ADMIN_PERMISSIONS = Object.freeze([
  "USERS_VIEW",
  "USERS_EDIT",
  "USERS_BAN",
  "PARTNER_MANAGE",
  "ORDERS_MANAGE",
  "PRODUCTS_MANAGE",
  "TICKETS_MANAGE",
  "NOTIFICATIONS_MANAGE",
  "DISCOUNTS_MANAGE",
  "ANALYTICS_VIEW",
  "LOGS_VIEW"
]);

module.exports = {
  ADMIN_PERMISSIONS,
  DEFAULT_ADMIN_PERMISSIONS
};
